# Generated by Django 3.0.1 on 2020-05-01 15:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='*Please type full name of your company', max_length=30)),
                ('est_year', models.CharField(blank=True, help_text='*optional', max_length=4)),
                ('hr_name', models.CharField(help_text='*required', max_length=30)),
                ('hr_phn', models.CharField(help_text='*required', max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('headquarters', models.CharField(blank=True, help_text='*optional', max_length=30)),
                ('about', models.TextField(blank=True, help_text='*optional', max_length=1000)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Intern', 'Internship'), ('Others', 'Others')], max_length=100)),
                ('designation', models.CharField(help_text='*required', max_length=100)),
                ('min_10_percent', models.FloatField(help_text='*In percent', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_12_percent', models.FloatField(help_text='*In percent', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_btech_cgpa', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('information_technology', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('mechanical', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('cse', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('ee', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('ece', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('civil', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('ctc', models.FloatField(help_text='In Lakhs')),
                ('bond_years', models.FloatField(help_text='*required')),
                ('bond_amount', models.FloatField(blank=True, help_text='*In Lakhs')),
                ('email', models.EmailField(help_text='*required', max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
