# Generated by Django 3.0.1 on 2020-05-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='no_of_backlogs',
            field=models.IntegerField(default=0),
        ),
    ]
