# Generated by Django 3.0.1 on 2020-05-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20200503_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bond_amount',
            field=models.FloatField(help_text='*In Lakhs'),
        ),
        migrations.AlterField(
            model_name='company',
            name='est_year',
            field=models.CharField(help_text='*optional', max_length=4),
        ),
        migrations.AlterField(
            model_name='company',
            name='headquarters',
            field=models.CharField(help_text='*optional', max_length=30),
        ),
    ]
