# Generated by Django 3.0.1 on 2020-05-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20200503_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_date_to_apply',
            field=models.DateField(default='2012-10-10'),
            preserve_default=False,
        ),
    ]
