# Generated by Django 3.0.1 on 2020-05-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_last_date_to_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='last_date_to_apply',
            field=models.DateField(blank=True),
        ),
    ]
