# Generated by Django 3.0.1 on 2020-04-27 06:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter Full Name', max_length=100)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', models.CharField(help_text='*Enter 10 digit mobile number', max_length=10, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)])),
                ('roll_no', models.CharField(help_text='*Enter University Roll No.', max_length=20, validators=[django.core.validators.MaxLengthValidator(20), django.core.validators.MinLengthValidator(8)])),
                ('branch', models.CharField(choices=[('IT', 'Information Technology'), ('CSE', 'Computer Science & Technology'), ('ECE', 'Electronics & Communication'), ('EE', 'Eletrical Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('MCA', 'Master of Computer Application')], help_text='Select the Department', max_length=100)),
                ('language', models.CharField(choices=[('C', 'C'), ('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('PHP', 'PHP'), ('Others', 'Others')], help_text='Select the language you know best', max_length=100)),
                ('dob', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('class_10', models.FloatField(help_text='Please enter 10th marks in %', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('class_12', models.FloatField(help_text='Please enter 10th marks in %', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('btech_cgpa', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('address', models.TextField(help_text='Please enter your permanent address', max_length=254)),
                ('placed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
