# Generated by Django 3.0.1 on 2020-04-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student',
            new_name='is_student',
        ),
    ]
