# Generated by Django 3.0.1 on 2020-04-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_student_is_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
