# Generated by Django 3.0.1 on 2020-04-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_is_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_student',
        ),
    ]
