# Generated by Django 3.0.1 on 2020-05-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_student_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='no_of_backlogs',
            field=models.IntegerField(default=0),
        ),
    ]
