# Generated by Django 3.0.1 on 2020-05-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_no_of_backlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', help_text='Please upload your recent photograph', upload_to='student_images/'),
        ),
    ]
