# Generated by Django 3.0.1 on 2020-05-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20200503_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='static/campusplacement/images/default.jpg', help_text='Please upload your recent photograph', upload_to='student_images/%Y/%m/%d/'),
        ),
    ]
