# Generated by Django 3.0.1 on 2020-05-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_student_placed_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('Information Technology', 'Information Technology'), ('Computer Science & Technology', 'Computer Science & Technology'), ('Electronics & Communication', 'Electronics & Communication'), ('Eletrical Engineering', 'Eletrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering')], help_text='Select the Department', max_length=100),
        ),
    ]
