# Generated by Django 3.0.1 on 2020-05-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20200504_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='language',
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('Information Technology', 'Information Technology'), ('Computer Science & Engineering', 'Computer Science & Engineering'), ('Electronics & Communication', 'Electronics & Communication'), ('Eletrical Engineering', 'Eletrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering')], help_text='Select the Department', max_length=100),
        ),
    ]
