# Generated by Django 3.0.1 on 2020-05-04 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_applied_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applied_Job',
        ),
    ]
