# Generated by Django 3.0.1 on 2020-05-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20200504_1416'),
        ('student', '0017_delete_applied_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='applied_companies',
            field=models.ManyToManyField(to='company.Company'),
        ),
    ]
